// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using HeroesProfile_GCP_ReplayParser;
//
//    var inputData = InputData.FromJson(jsonString);

namespace HeroesProfile_GCP_ReplayParser
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class InputData
    {
        [JsonProperty("input")]
        public string Input { get; set; }

        [JsonProperty("fingerprint")]
        public string Fingerprint { get; set; }

        [JsonProperty("parseType")]
        public string ParseType { get; set; }

        [JsonProperty("bucket")]
        public string Bucket { get; set; }
    }

    public partial class InputData
    {
        public static InputData FromJson(string json) => JsonConvert.DeserializeObject<InputData>(json, HeroesProfile_GCP_ReplayParser.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this InputData self) => JsonConvert.SerializeObject(self, HeroesProfile_GCP_ReplayParser.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
